#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-guard
Version  : 2.13.0
Release  : 7
URL      : https://rubygems.org/downloads/guard-2.13.0.gem
Source0  : https://rubygems.org/downloads/guard-2.13.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-guard-bin
BuildRequires : ruby
BuildRequires : rubygem-formatador
BuildRequires : rubygem-pry
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-thor

%description
:exclamation::exclamation: Guard is [currently accepting more maintainers/contributors](https://groups.google.com/forum/#!topic/guard-dev/2Td0QTvTIsE). :exclamation::exclamation:

%package bin
Summary: bin components for the rubygem-guard package.
Group: Binaries

%description bin
bin components for the rubygem-guard package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n guard-2.13.0
gem spec %{SOURCE0} -l --ruby > rubygem-guard.gemspec

%build
gem build rubygem-guard.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
guard-2.13.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/guard-2.13.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/bin/_guard-core
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/bin/guard
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/images/failed.png
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/images/pending.png
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/images/success.png
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/aruba_adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/cli.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/cli/environments/bundler.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/cli/environments/evaluate_only.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/cli/environments/valid.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/commander.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/commands/all.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/commands/change.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/commands/notification.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/commands/pause.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/commands/reload.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/commands/scope.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/commands/show.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/config.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/deprecated/dsl.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/deprecated/evaluator.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/deprecated/guard.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/deprecated/guardfile.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/deprecated/watcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/dsl.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/dsl_describer.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/dsl_reader.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/group.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/guardfile.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/guardfile/evaluator.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/guardfile/generator.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/interactor.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/internals/debugging.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/internals/groups.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/internals/helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/internals/plugins.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/internals/queue.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/internals/scope.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/internals/session.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/internals/state.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/internals/tracing.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/internals/traps.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/jobs/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/jobs/pry_wrapper.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/jobs/sleep.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/notifier.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/options.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/plugin.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/plugin_util.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/rake_task.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/runner.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/templates/Guardfile
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/terminal.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/ui.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/ui/colors.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/lib/guard/watcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/man/guard.1
/usr/lib64/ruby/gems/2.3.0/gems/guard-2.13.0/man/guard.1.html
/usr/lib64/ruby/gems/2.3.0/specifications/guard-2.13.0.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/_guard-core
/usr/bin/guard
